apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  storageClassName: ""
  accessModes: 
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongo.storageSize }}