apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment  
  namespace: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: kthwang3/todo-app:latest
        ports:
          - containerPort: 3000
        env:
        - name: DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: DATABASE_URI
