- name: Configure todo app server on EC2
  hosts: web
  become: true
  tasks:
    - name: Create app directory
      file:
        path: /home/ubuntu/app
        state: directory
    - name: Install Docker
      shell: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sh get-docker.sh
      args:
        creates: /usr/bin/docker
    - name: Install AWS CLI
      shell: |
      curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      apt install unzip -y
      unzip awscliv2.zip
      ./aws/install
      args:
        creates: /usr/local/bin/aws
    - name: Add ubuntu user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes
    - name: Copy docker-compose.yml to the server
      copy:
        src: ../docker-compose.yml
        dest: /home/ubuntu/app/docker-compose.yml
    - name: Copy .env to the server
      copy:
        src: ../.env
        dest: /home/ubuntu/app/.env
    - name: Create nginx directory
      file:
        path: /home/ubuntu/app/nginx
        state: directory
    - name: Copy nginx config to the server
      copy:
        src: ../nginx/nginx.conf
        dest: /home/ubuntu/app/nginx/nginx.conf
    - name: Run docker compose up -d
      shell:
        cmd: docker compose up -d
        chdir: /home/ubuntu/app
        


